---
- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Install git-up
  pip:
    name: '{{ item }}'
    executable: '{{ pip_executable | default(omit) }}'
    state: present
  with_items:
    - git-up
    - shovel
    - ipython
    - docker-py

- name: Create config directories
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('haad') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: directory
  with_items:
    - path: /home/haad/.ssh
      mode: '0700'
    - path: /home/haad/.config
      mode: '0700'
    - path: /home/haad/bin
      mode: '0755'
    - path: /home/haad/Devel
      mode: '0755'
    - path: /home/haad/Devel/go
      mode: '0755'


- name: Deploy required templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('haad') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
    - src: zshrc.j2
      dest: /home/haad/.zshrc
    - src: tmux.conf.j2
      dest: /home/haad/.tmux.conf

    - src: terraformrc.j2
      dest: /home/haad/.terraformrc

    - src: gitconfig.j2
      dest: /home/haad/.gitconfig
    - src: gitignore.j2
      dest: /home/haad/.gitignore
    - src: sshconfig.j2
      dest: /home/haad/.ssh/config

    - src: vimrc.bundles.local.j2
      dest: /home/haad/.vimrc.bundles.local
    - src: vimrc.local.j2
      dest: /home/haad/.vimrc.local


#    - src: procmailrc.j2
#      dest: /home/haad/.procmailrc
#    - src: fetchmailrc.j2
#      dest: /home/haad/.fetchmailrc

#- name: Setup fetchmail cron job
#  cron:
#    name: "Check mails for user {{ user.name }}"
#    user: "{{ user.name }}"
#    minute: '*/15'
#    job: /usr/bin/fetchmail >/dev/null 2>&1

- name: Install oh-my-zsh to user directory
  become_user: haad
  git:
    repo: https://github.com/haad/oh-my-zsh.git
    dest: /home/haad/.oh-my-zsh
  register: ohmyzsh
  until: ohmyzsh is success
  retries: 5
  delay: 2

- include: "{{ os_playbook }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - default.yml
  loop_control:
    loop_var: os_playbook

- name: Install VapourNvim to user directory
  become_user: haad
  git:
    repo: https://github.com/haad/VapourNvim.git
    dest: /home/haad/.config/nvim
  register: vapournvim
  until: vapournvim is success
  retries: 5
  delay: 2



