- name: service.chrony
  src: https://github.com/Chillisystems/ansible-chrony.git
  scm: git
  version: master
  path: ./dist

- name: setup.asdf
  src: https://github.com/cimon-io/ansible-role-asdf.git
  scm: git
  version: master
  path: ./dist

- name: service.docker
  src: https://github.com/geerlingguy/ansible-role-docker
  scm: git
  version: 4.1.1
  path: ./dist

- name: service.prometheus
  src: https://github.com/cloudalchemy/ansible-prometheus
  scm: git
  version: 4.0.0
  path: ./dist

- name: service.prometheus-blackbox
  src: https://github.com/cloudalchemy/ansible-blackbox-exporter
  scm: git
  version: 1.0.0
  path: ./dist

# - name: service.grafana-cloud-agent
#   src: https://github.com/haad/ansible-role-grafana_agent
#   scm: git
#   version: main
#   path: ./dist

- name: systemd-service
  scm: git
  src: https://github.com/lablabs/ansible-role-systemd-service.git
  version: 1.0.0
  path: ./dist
