---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Create default admin accounts
  become: yes
  user:
    state: present
    createhome: yes
    generate_ssh_key: yes
    name: "{{ item.name }}"
    groups: "{{ item.groups | default(omit) }}"
    home: "/home/{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    append: "{{ item.append | default(false) }}"
  with_items:
    - "{{ server_users }}"

- name: Add ssh pub keys to user
  become: yes
  authorized_key:
    state: present
    manage_dir: yes
    key: "{{ lookup('file', '../files/keys/' + item.name + '.pub') }}"
    user: "{{ item.name }}"
  with_items:
    - "{{ server_users }}"

- name: Enable sudo without password for admin users in group %sudo
  become: yes
  lineinfile:
    dest: '{{ sudoers_path }}'
    state: present
    regexp: '^%{{ sudo_group }}'
    line: "%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'

- name: create concatenated keys file
  become: no
  local_action:
    module: assemble
    src: ../roles/setup.users/files/keys/
    dest: /tmp/ssh_keys_file

- name: set up authorized_keys
  authorized_key:
    user: root
    key: "{{ lookup('file', '/tmp/ssh_keys_file') }}"
    exclusive: yes
