---

- name: Deploy common roles
  hosts: "{{ deploy_hosts }}"
  become: true
  gather_facts: true
  tags: play:basic
  environment: "{{ deploy_env_vars | default({}) }}"
  vars_files:
    - ../vars/common-secrets.yml
  tasks:
    - include_role:
        name: setup.haad-home
      tags: role:setup.users
