- name: Deploy Monitoring Stack Grafana + Exporters
  hosts: "{{ deploy_hosts }}"
  become: true
  gather_facts: true
  tags: play:basic
  environment: "{{ deploy_env_vars | default({}) }}"
  vars_files:
    - ../vars/common-secrets.yml
  tasks:
    # - include_role:
    #     name: service.prometheus
    #   tags: role:prometheus.deploy
    - include_role:
        name: service.grafana-cloud-agent
      tags: role:grafana-cloud-agent
    - include_role:
        name: service.prometheus-blackbox
      tags: role:prometheus-blackbox.deploy